### ISSUE TITLE
Cannot change dotSize and penColor dynamically

### ISSUE THREAD

**Issue by egodefroy** [kiwi-bop/flutter_signature_pad#1]
When building with a new strokeWidth or color in the options, changes are not effective.

Following your example, when setting state with a new strokeWidth or a new color, the drawing is done with the same initial values.

```
selectColor(Color value) {
     setState(() => penColor = value); // does not change color of the stroke
 }
...
Widget build(BuildContext context) {
    var sign = Signature(
      color: penColor,
      strokeWidth: dotSize,
    );
```
How can we change dynamically these values ?

**Comment by jaumard** [comment]
Hi, 
You're right there a bug on dynamic changes, I'm working on it right now :) thanks for the report
