### ISSUE TITLE
How to make signature_pad unscrollable?

### ISSUE THREAD

**Issue by jazzbpn** [kiwi-bop/flutter_signature_pad#10]
I put the signature widget inside the TabBarView(). So when I try to do the signature the view scrolls and is little bit laggy(Start signature after leaving the first step).

`@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text Field Focus'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        // child: makeList(),
        child: Signature(
          color: Colors.black, // Color of the drawing path
          strokeWidth: 2.0, // with
          backgroundPainter:
              null, // Additional custom painter to draw stuff like watermark
          onSign: null, // Callback called on user pan drawing
          key:
              null, // key that allow you to provide a GlobalKey that'll let you retrieve the image once user has signed
        ),
      ),
    );
  }`

**Comment by rendramhardika** [comment]
i've also got same issue. i put my signature widget inside scrollview. when i try to sign vertically, the signature was not drew, it scrolling instead signed..

**Comment by jaumard** [comment]
I never used it on a scroll parent before, but from what I can see I just use GestureDetector, if a parent is getting the event before the signature widget I have no idea what I can do...

**Comment by Burgomehl** [comment]
Maybe this article could solve the problem: https://www.davidanaya.io/flutter/combine-multiple-gestures.html

**Comment by jaumard** [comment]
Look like the way to go @Burgomehl ! Thanks for the interesting link :) 
If anyone want to do a PR in that way feel free, I'll not have free time to do it myself soon

**Comment by langaro** [comment]
I wrapped it on a Dialog.

**Comment by tony123S** [comment]
Anyone has the solution?

**Comment by tony123S** [comment]
I have found the solution. But failed to push my code in new branch

> remote: Permission to kiwi-bop/flutter_signature_pad.git denied to tony123S.

**Comment by omkarkhalipe** [comment]
@tony123S I just checked your fork but the code looks same, can you explain what you did to fix it or can you push the changes on your git

**Comment by tony123S** [comment]
@omkarkhalipe  Add `onVerticalDragStart`,`onVerticalDragUpdate`,`onVerticalDragEnd`

**Comment by jaumard** [comment]
there is a pending PR fixing this apparently, so if people want to test and give feedback about this don't hesitate. https://github.com/kiwi-bop/flutter_signature_pad/pull/19
