### ISSUE TITLE
Save to image 

### ISSUE THREAD

**Issue by LucaGabi** [kiwi-bop/flutter_signature_pad#11]
Hi, can I save the signature to file ?

**Comment by ilhamamirullah** [comment]
@LucaGabi Hey can you explain how to do it? I need it to upload to server

**Comment by Marcosmaliki** [comment]
If you must use the file path to upload then try this:

`
import 'dart:io';
import 'dart:ui' as ui;
import 'package:path_provider/path_provider.dart';

  var appDocDir = await getApplicationDocumentsDirectory();
        final image = await signKey.currentState?.getData();
        var data = await image?.toByteData(format: ui.ImageByteFormat.png);
String fullPath = appDocDir.path + '/signature.png';
        File file = File(fullPath);
        final raf = file.openSync(mode: FileMode.write);
        raf.writeFromSync(data!.buffer.asUint8List());
        await raf.close();
       debugprint('file saved!');
