### ISSUE TITLE
base64_encode

### ISSUE THREAD

**Issue by ziasultan2** [kiwi-bop/flutter_signature_pad#12]
image is not converting into base64_encode completely only a few portions are saving

**Comment by ziasultan2** [comment]
Thank you for your reply bro. I solve the problem. I made a mistake I put the value on static variable and then try to access it from another state that's why it was not showing the full image only a part of image.
Thank you bro

**Comment by jaumard** [comment]
Ok cool !!! Glad you make it work :) 

Cheers
