### ISSUE TITLE
Can I set the image background color?

### ISSUE THREAD

**Issue by Lidinghua** [kiwi-bop/flutter_signature_pad#13]
The default is now black when I save to remote server and browse it
the code is following:
               /// save image
                FormData picData = new FormData();
                final sign = _sign.currentState;
                final image = await sign.getData();
                var data = await image.toByteData(format: UI.ImageByteFormat.png);

                final dir = (await getApplicationDocumentsDirectory());
                var file = await File('${dir.path}/sign.png').writeAsBytes(data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
                ///  compresse
                var compressedImage = await FlutterImageCompress.compressAndGetFile(
                file.absolute.path,
                '${dir.path}/temp.jpg',
                minWidth: 200,
                minHeight: 500,
                quality: 100,
                );
                var uploadFile = new UploadFileInfo(compressedImage, basename(compressedImage.path));
                picData.add('${file.absolute.path}', uploadFile);

                DioUtil().request(Method.post, Api.ATTACHMENT_UPLOAD, data: picData).then((resp){
                  resp.data = jsonDecode(resp.data);
                  Map map = Map.from({'pic':resp.data[0]['id']});
                  Navigator.pop(context, map);
                })

**Comment by jaumard** [comment]
hello,

What do you mean by `The default is now black when I save to remote server and browse it` ? is the picture all black or just the writing ? can you share the widget configuration too ?

**Comment by Lidinghua** [comment]
class _SignPageState extends State<SignPage> {
  final _sign = GlobalKey<SignatureState>();
  ShapeBorder _buttonShape;

  @override
  Widget build(BuildContext context) {
    final ButtonThemeData buttonTheme = ButtonTheme.of(context).copyWith(
        shape: _buttonShape
    );

    return Scaffold(
      appBar: AppBar(
      ),
      body: Container(
        child: Signature(
          color: Colors.red,
          key: _sign,
          strokeWidth: 2.0,
          onSign: () {},
        ),
      ),
      bottomNavigationBar: ButtonTheme.fromButtonThemeData(
        data: buttonTheme,
        child: ButtonBar(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            RaisedButton(
              child: const Text('clear'),
              onPressed: () {
                final sign = _sign.currentState;
                sign.clear();
              },
            ),
            RaisedButton(
              child: const Text('finish'),
              onPressed: () {
                save();
              },
            ),
          ],
        ),
      ),
    );
  }
}
//I wrote this
![IMG_20191127_104034](https://user-images.githubusercontent.com/46698923/69688972-8d82fc80-1102-11ea-9567-5819ddf81b63.jpg)
//It looks like this
![IMG_20191127_104015](https://user-images.githubusercontent.com/46698923/69689009-ab506180-1102-11ea-970e-928fa7c0be70.jpg)

**Comment by jaumard** [comment]
You can use backgroundPainter to put a background color.  https://github.com/kiwi-bop/flutter_signature_pad/blob/master/lib/flutter_signature_pad.dart#L15
