### ISSUE TITLE
Image to base64

### ISSUE THREAD

**Issue by viktor-morin** [kiwi-bop/flutter_signature_pad#20]
Thanks for a nice lib!

I have one issue trying to save the picture to a format i can upload.
For example, saving the image as base64, the result is not valid as an image.

Code:
```
var image = await _sign.currentState.getData();
var data = await image.toByteData();

var dataList = Uint8List.view(data.buffer);
var base64String = base64.encode(dataList);
```

**Comment by jaumard** [comment]
Hello :)

Here is what I do and use in production https://github.com/kiwi-bop/flutter_signature_pad/blob/master/example/lib/main.dart#L98-L103

No problem with that code

**Comment by viktor-morin** [comment]
Thanks, works perfect! 
Was searching internet for the right way to encode it, but couldn't find it!
