### ISSUE TITLE
build error when testing the example code

### ISSUE THREAD

**Issue by The-five-stooges** [kiwi-bop/flutter_signature_pad#21]
here is the error log:
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_signature_pad-2.0.2/lib/flutter_signature_pad.dart:23:20: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
    return context.findAncestorStateOfType<SignatureState>();

**Comment by augugusto** [comment]
i haven't tried building the exmaple, but from what i can see you have a '/' at the begining of that path. is that normal ? i'm on linux so i can't test. also from some very light googling it seems like you might have to update your sdk

**Comment by jaumard** [comment]
Should be good with #25 example have been updated
