### ISSUE TITLE
how get only the drawing

### ISSUE THREAD

**Issue by fabioebner** [kiwi-bop/flutter_signature_pad#24]
I opened the signature in a new page(he took the whole page), so If my user draw at the bottom in a portrait mode when I catch the image he took the whole page and the draw in the bottom, can I crop to show only the drawer with a few space around? tks

**Comment by jaumard** [comment]
My advice would be to resize the signature to be smaller and put border for users to know signature boundaries. But once you retrieve the image you can crop it if you want for sure. But there is nothing built in for that in this package.
