### ISSUE TITLE
How to set background image from asset?

### ISSUE THREAD

**Issue by ilhamamirullah** [kiwi-bop/flutter_signature_pad#26]
I want to put a background image on the pad or onto image after converted.
I know it has a BackgroundPainter, but I don't know how to put a background image.
Please need your advice.
Thank you

**Comment by jibinjayachandran** [comment]
How do we put background color. When I try to save to Image, its having trasparent background. Please help me to add a white background for the image.

**Comment by jaumard** [comment]
Use the `backgroundPainter` parameter to either draw an image background or put a default color, check the example project if you need an example
