### ISSUE TITLE
Dot not working after adding "onVerticalDrag"

### ISSUE THREAD

**Issue by raymondnexsoftech** [kiwi-bop/flutter_signature_pad#29]
I found that the problem is from the commit "https://github.com/kiwi-bop/flutter_signature_pad/commit/64644398bd871251ecd41a0befcea3fab6afb54b" that implementing the "onVerticalDrag" series.
After adding Vertical Drag detection, Flutter will have a delay to recognize the gesture is signing. That's why the dot is not working.
For a quick fix solution, I suggest to adding an option to enable / disable "onVerticalDrag" when user call the constructor so that user can choose to disable the vertical drag (for fixing the dot problem) or enable it (for using in scrollview)

Of course an ultimate solution to fix both will be better.

**Comment by jaumard** [comment]
Should be fixed in https://github.com/kiwi-bop/flutter_signature_pad/pull/25
