### ISSUE TITLE
not working on Flutter 1.25.0-8.2.pre

### ISSUE THREAD

**Issue by woshitom** [kiwi-bop/flutter_signature_pad#30]
Hi,

Everything was working perfectly until I updated to flutter 1.25.0-8.2.pre. No error are thrown but nothing is being drawn. I think it's just a matter of painting because I'm still able to see sign.points.length increase. Any idea?

**Comment by jaumard** [comment]
Working a flutter 2.5.0 so closing this, don't hesitate to reopen
