### ISSUE TITLE
Migration to null-safety

### ISSUE THREAD

**Issue by bradsb** [kiwi-bop/flutter_signature_pad#32]
Flutter 2.0 is stable now featuring null-safety
https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65

Are there plans to migrate this package to null-safety?

**Comment by psrcek** [comment]
I would really appreciate it if you migrated this package as our application depends on it and this package is preventing us from migrating.

*+1*

**Comment by jaumard** [comment]
It will be migrated to null safety for sure, we depends on it too :) but nothing plan so far. If you have time to contribute don't hesitate to make a PR! I'll gladly review and merge it.

**Comment by jaumard** [comment]
Done in 3.0.0 don't hesitate if there is any issues
