### ISSUE TITLE
Flutter 3.0.0 update necessary

### ISSUE THREAD

**Issue by lukasloh** [kiwi-bop/flutter_signature_pad#35]
Due to the new Flutter version 3.0.0, and their changes to the way the instance property on bindings work the package requires an upgrade to silence the warnings.

You can read more about it here - https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0

This is the warning that I'm receiving from the package:
```
./../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_signature_pad-3.0.0/lib/flutter_signature_pad.dart:60:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which
excludes null.
```

Thanks!

**Comment by jaumard** [comment]
Fixed on 3.0.1
