### ISSUE TITLE
Plugin unusable after last flutter release

### ISSUE THREAD

**Issue by Jordanlelay** [kiwi-bop/flutter_signature_pad#5]
I was using the plugin on an android apk which was fine but after the last release, the pad is not working correctly. I attach you a screenshot of the example app of the plugin
![screenshot_20190228-122907](https://user-images.githubusercontent.com/43350109/53563616-df3b2e00-3b54-11e9-95db-2e903bf559bc.jpg)

**Comment by agarzas** [comment]
I am also experiencing this issue

<img width="327" alt="screen shot 2019-02-28 at 11 45 34 pm" src="https://user-images.githubusercontent.com/43526819/53618968-3243ce00-3bb3-11e9-8945-d9daabc7e9c6.png">

**Comment by jaumard** [comment]
Hi guys ! Is this happening on android, iOS or both ? I'm not experiencing this on iOS simulator for example. Did you try a Flutter clean or even uninstall the app ? I know a lot of people had to do that with the new release (not only related to this plugin)

**Comment by Jordanlelay** [comment]
> Hi guys ! Is this happening on android, iOS or both ? I'm not experiencing this on iOS simulator for example. Did you try a Flutter clean or even uninstall the app ? I know a lot of people had to do that with the new release (not only related to this plugin)

Hi Jaumard! I'm currently experiencing this on Android. I've clean, uninstall, rebuild ... nothing work for me on android. And yes you're definitely right, the last Flutter update broke multiple plugins that use the CustomPainter especially. I've searched quite a bit around, but I'm not sure why this happens

**Comment by xascis** [comment]
Hi! 
Same here. Tested in Android emulator and Samsung Tablet.

**Comment by KNightING** [comment]
Hey!
I reference your code to write for my signature pad and I have same wrong.
And I find a [solution](https://github.com/flutter/flutter/issues/28142#issuecomment-465395765) to work for me.

Try using `flutter build apk --target-platform=android-arm64` to build an arm64 APK.

**Comment by jaumard** [comment]
Ho nice finding @KNightING ! so I guess they changed the way they build apk with the last stable version. let's wait until they fix the bug on their side then :)

**Comment by MauriPastorini** [comment]
Hello, I didnt have this problem... Why could it be? Because of my specific cellphone?

```
flutter doctor
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.3)
[√] Connected device (1 available)
```

**Comment by jaumard** [comment]
Because of https://github.com/flutter/flutter/issues/28142 the last stable version of flutter has a bug

**Comment by jaumard** [comment]
Closing as it's not a problem on this package :)

**Comment by korgara** [comment]
Seems like it's fixed in latest flutter master channel (Flutter 1.4.5-pre.12 • channel master •)
in terminal run `$ flutter channel master`, then `$ flutter upgrade`, build a new .apk and there we go

**Comment by jaumard** [comment]
That's good news @korgara !!! thanks for the update !

**Comment by Jordanlelay** [comment]
Thanks for the update!
