### ISSUE TITLE
When i call  the method getData, backgroundPainter is null  and exception was thrown

### ISSUE THREAD

**Issue by violetmoonmm** [kiwi-bop/flutter_signature_pad#6]
When i call  the method getData, backgroundPainter is null  and crash

I/flutter (12444): When the exception was thrown, this was the stack:
I/flutter (12444): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (12444): #1      SignatureState.getData (package:flutter_signature_pad/flutter_signature_pad.dart:91:30)
I/flutter (12444): #2      SignaturePageState.build.<anonymous closure> (package:flutter_sa/pages/sign.dart:148:73)

**Comment by jaumard** [comment]
You're right ! We never used it without it so we didn't notice :) thanks ! I'll fix this !

**Comment by jaumard** [comment]
Fixed in 2.0.0+1 :)
