### ISSUE TITLE
Issue with getData() not being declared async

### ISSUE THREAD

**Issue by LittleVigilante** [kiwi-bop/flutter_signature_pad#7]
Hi guys! This is a great Flutter plugin. I had to modify your dart file to get it to work for me, though. The getData() method returns a Future<Image>, but is not declared asynchronous. So my compiler failed and had an issue with the Image being returned not being of type Future. Is there another way around this? Adding the 'async' tag to the getData() method in the dart file worked for me, but perhaps I just am not using it correctly? Flutter 1.1.9 Dart 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

**Comment by jaumard** [comment]
Hey @LittleVigilante ! 
`getData` doesn't need to specify `async` as it doesn't use `await` and yes it return a Future which is correct :) 

Maybe you have an issue on your code, here you have a usage example on how retrieve the image data https://github.com/kiwi-bop/flutter_signature_pad/blob/master/example/lib/main.dart#L99 

Check it out and let us know
