### ISSUE TITLE
ByteDataView

### ISSUE THREAD

**Issue by ysoofiyani** [kiwi-bop/flutter_signature_pad#8]
Hey

I can not use data as a file for saving.
var data = await image.toByteData(format: ui.ImageByteFormat.png);
when I use "File file = data" I got an error that data is ByteDataView.
How can I convert data to file ?????

**Comment by Saik0s** [comment]
Here how can you save data to file:
```dart
final dir = (await getApplicationDocumentsDirectory()).path;
final file = File('$dir/image.png');
final buffer = data.buffer;
await File(path).writeAsBytes(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
```

**Comment by jaumard** [comment]
Hello, 

Probably your `image` variable is wrong. 
It's because you need to do it like this: 
https://github.com/kiwi-bop/flutter_signature_pad/blob/master/example/lib/main.dart#L99
